### ISSUE TITLE
 Are you aware of shio?

### ISSUE THREAD

**Issue by algermissen** [mgattozzi/chiisai#1]
This seems a lot likeminded with shio: https://github.com/mehcode/shio-rs

If you know it already, can you clarify how your framework intends to differ?

**Comment by mgattozzi** [comment]
I was completely unaware it even existed. I mostly whipped this up for use at work and figured it would be useful for others if they needed something like it. This isn't really meant for anything beyond microservices; so no websites, template rendering etc. will be supported out of the box.

**Comment by algermissen** [comment]
Thanks - sounds like a lot of overlap to me. Maybe you should join forces :-)

**Comment by mgattozzi** [comment]
@algermissen maybe! Thanks for pointing it out!
